name: 'Transform translations for the ATM'
description: 'Transform a common translation JSON files to the ATM JSON format.'
inputs:
  folder_with_simple_jsons:  # id of input
    description: 'The folder with input translation files'
    required: true
    default: 'locales/source'
  folder_with_core_translations:  # id of input
    description: 'The folder with results of conversion translation files'
    required: true
    default: 'locales'
runs:
  using: 'node16'
  main: 'dist/index.js'
