name: 'Transform translations for the ATM'
description: 'Transform a common translation JSON files to the ATM JSON format.'
inputs:
  folder_with_simple_jsons:  # id of input
    description: 'The folder with input translation files'
    required: true
    default: 'locales/source'
  folder_with_core_translations:  # id of input
    description: 'The folder with results of conversion translation files'
    required: true
    default: 'locales'
  git_user_name:
    description: "The user name for commits"
    required: false
    default: 'github-actions'
  git_user_email:
    description: "The user email for commits"
    required: false
    default: 'github-actions@github.com'
outputs:
  is_commit_available: # output will be available to future steps
    description: 'The indicator of available commit after transformation'
runs:
  using: 'node16'
  main: 'dist/index.js'
